services:
  - type: web
    name: ai-recruiter
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_PROJECT_ID
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ACCESS_TOKEN
        sync: false
        optional: true
    healthCheckPath: /
    autoDeploy: true
