services:
  - type: web
    name: ai-recruiter
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_PROJECT_ID
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
